#!/bin/env sh

# Get pywal colors if available
COLORS=$HOME/.cache/wal/sequences
if [ -f "$COLORS" ]; then
	(cat "$COLORS" &)
fi

SCRIPT=`readlink -f "$0"`
SCRIPT_DIR=`dirname "$SCRIPT"`
TOFI="$SCRIPT_DIR/tofib"

# Don't launch if tofi is already running
pgrep tofi &> /dev/null
if [[ $? == 0 ]]; then
	exit 1
fi

$TOFI --applications | sort -u -r | \
	fzf --bind "ctrl-w:reload('$TOFI' --windows | sort -u -r)" \
		--bind "ctrl-a:reload('$TOFI' --applications | sort -u -r)" \
		--bind "ctrl-r:reload('$TOFI' --recent | sort -u -r)" \
		--bind "ctrl-s:reload('$TOFI' --shell | sort -u -r)" \
		--bind "ctrl-e:reload('$TOFI' --recent --shell --applications --windows | sort -u -r)" \
		--preview "echo '{}' | '$TOFI' --preview" \
		--preview-window ":0" | \
	$TOFI
